// Auto-generated structural Verilog from SPICE subckt '8b_mult'
// Generated by gen_mult_from_spice.py

// Black-box stub for cell '8b_FA_ripple' derived from SPICE .subckt
(* black_box, keep_hierarchy = "yes" *)
module fa8b_rev (
    inout wire VDD,
    inout wire VSS,
    inout wire c0_f, //
    inout wire c0_b, //
    inout wire c0_f_not, //
    inout wire c0_b_not, //
    inout wire s0, //
    inout wire b0, //
    inout wire s0_not, //
    inout wire b0_not, //
    inout wire a0_f, //
    inout wire a0_b, //
    inout wire a0_not_b, //
    inout wire a0_not_f, //
    inout wire b1, //
    inout wire s1, //
    inout wire b1_not, //
    inout wire s1_not, //
    inout wire a1_f, //
    inout wire a1_b, //
    inout wire a1_not_f, //
    inout wire a1_not_b, //
    inout wire s2, //
    inout wire b2, //
    inout wire s2_not, //
    inout wire b2_not, //
    inout wire a2_b, //
    inout wire a2_f, //
    inout wire a2_not_f, //
    inout wire a2_not_b, //
    inout wire s3, //
    inout wire b3, //
    inout wire s3_not, //
    inout wire b3_not, //
    inout wire a3_b, //
    inout wire a3_f, //
    inout wire a3_not_f, //
    inout wire a3_not_b, //
    inout wire s4, //
    inout wire b4, //
    inout wire b4_not, //
    inout wire s4_not, //
    inout wire a4_b, //
    inout wire a4_f, //
    inout wire a4_not_b, //
    inout wire a4_not_f, //
    inout wire b5, //
    inout wire s5, //
    inout wire b5_not, //
    inout wire s5_not, //
    inout wire a5_f, //
    inout wire a5_b, //
    inout wire a5_not_b, //
    inout wire a5_not_f, //
    inout wire b6,  //
    inout wire s6, //
    inout wire b6_not,//
    inout wire s6_not, //
    inout wire a6_f, //
    inout wire a6_b, //
    inout wire a6_not_b, //
    inout wire a6_not_f, //
    inout wire s7, //
    inout wire b7, //
    inout wire b7_not, //
    inout wire s7_not, //
    inout wire a7_b, //
    inout wire a7_f, //
    inout wire a7_not_b, //
    inout wire a7_not_f, //
    inout wire z,
    inout wire z_not,
    inout wire c7,
    inout wire c7_not
);
    // Implementation comes from custom cell layout / transistor-level netlist.
endmodule

// Black-box stub for cell 'CCNOT' derived from SPICE .subckt
(* black_box, keep_hierarchy = "yes" *)
module CCNOT (
    inout wire a,
    inout wire b,
    inout wire VSS,
    inout wire VDD,
    inout wire a_not,
    inout wire b_not,
    inout wire r,
    inout wire c,
    inout wire p,
    inout wire q,
    inout wire r_not,
    inout wire p_not,
    inout wire q_not,
    inout wire c_not
);
    // Implementation comes from custom cell layout / transistor-level netlist.
endmodule

// Top-level structural netlist reconstructed from SPICE
module mult8b_rev (
    inout wire VSS,
    inout wire VDD,
    inout wire a0_not,
    inout wire a0,
    inout wire a1_not,
    inout wire a1,
    inout wire a2_not,
    inout wire a2,
    inout wire a3_not,
    inout wire a3,
    inout wire a4_not,
    inout wire a4,
    inout wire a5_not,
    inout wire a5,
    inout wire a6_not,
    inout wire a6,
    inout wire a7_not,
    inout wire a7,
    inout wire b0_not,
    inout wire b0,
    inout wire b1_not,
    inout wire b1,
    inout wire p0,
    inout wire p0_not,
    inout wire p1,
    inout wire p1_not,
    inout wire b0_r1_b,
    inout wire b0_r1_b_not,
    inout wire b0_q0,
    inout wire b0_q0_not,
    inout wire b0_p0,
    inout wire b0_p0_not,
    inout wire b0_q1,
    inout wire b0_q1_not,
    inout wire b0_p1,
    inout wire b0_p1_not,
    inout wire b0_q2,
    inout wire b0_q2_not,
    inout wire b0_p2,
    inout wire b0_p2_not,
    inout wire b0_q3,
    inout wire b0_q3_not,
    inout wire b0_p3,
    inout wire b0_p3_not,
    inout wire b0_q4,
    inout wire b0_q4_not,
    inout wire b0_p4,
    inout wire b0_p4_not,
    inout wire b0_q5,
    inout wire b0_q5_not,
    inout wire b0_p5,
    inout wire b0_p5_not,
    inout wire b0_q6,
    inout wire b0_q6_not,
    inout wire b0_p6,
    inout wire b0_p6_not,
    inout wire b0_q7,
    inout wire b0_q7_not,
    inout wire b0_p7,
    inout wire b0_p7_not,
    inout wire b1_q7,
    inout wire b1_q7_not,
    inout wire b1_p7,
    inout wire b1_p7_not,
    inout wire b1_q6,
    inout wire b1_q6_not,
    inout wire b1_p6,
    inout wire b1_p6_not,
    inout wire b1_q5,
    inout wire b1_q5_not,
    inout wire b1_p5,
    inout wire b1_p5_not,
    inout wire b1_q4,
    inout wire b1_q4_not,
    inout wire b1_p4,
    inout wire b1_p4_not,
    inout wire b1_q3,
    inout wire b1_q3_not,
    inout wire b1_p3,
    inout wire b1_p3_not,
    inout wire b1_q2,
    inout wire b1_q2_not,
    inout wire b1_p2,
    inout wire b1_p2_not,
    inout wire b1_q1,
    inout wire b1_q1_not,
    inout wire b1_p1,
    inout wire b1_p1_not,
    inout wire b1_q0,
    inout wire b1_q0_not,
    inout wire b1_p0,
    inout wire b1_p0_not,
    inout wire b1_c0,
    inout wire b1_c0_not,
    inout wire b1_c1,
    inout wire b1_c1_not,
    inout wire b1_c2,
    inout wire b1_c2_not,
    inout wire b1_c3,
    inout wire b1_c3_not,
    inout wire b1_c4,
    inout wire b1_c4_not,
    inout wire b1_c5,
    inout wire b1_c5_not,
    inout wire b1_c6,
    inout wire b1_c6_not,
    inout wire b1_c7,
    inout wire b1_c7_not,
    inout wire b0_c7,
    inout wire b0_c7_not,
    inout wire b0_c6,
    inout wire b0_c6_not,
    inout wire b0_c5,
    inout wire b0_c5_not,
    inout wire b0_c4,
    inout wire b0_c4_not,
    inout wire b0_c3,
    inout wire b0_c3_not,
    inout wire b0_c2,
    inout wire b0_c2_not,
    inout wire b0_c1,
    inout wire b0_c1_not,
    inout wire b0_c0,
    inout wire b0_c0_not,
    inout wire b2_c0,
    inout wire b2_c0_not,
    inout wire b2_q0,
    inout wire b2_q0_not,
    inout wire b2_p0,
    inout wire b2_p0_not,
    inout wire b2_q1,
    inout wire b2_q1_not,
    inout wire b2_p1,
    inout wire b2_p1_not,
    inout wire b2_c1,
    inout wire b2_c1_not,
    inout wire b2_q2,
    inout wire b2_q2_not,
    inout wire b2_p2,
    inout wire b2_p2_not,
    inout wire b2_q3,
    inout wire b2_q3_not,
    inout wire b2_p3,
    inout wire b2_p3_not,
    inout wire b2_q4,
    inout wire b2_q4_not,
    inout wire b2_p4,
    inout wire b2_p4_not,
    inout wire b2_q5,
    inout wire b2_q5_not,
    inout wire b2_p5,
    inout wire b2_p5_not,
    inout wire b2_q6,
    inout wire b2_q6_not,
    inout wire b2_p6,
    inout wire b2_p6_not,
    inout wire b2_q7,
    inout wire b2_q7_not,
    inout wire b2_p7,
    inout wire b2_p7_not,
    inout wire b2_c3,
    inout wire b2_c3_not,
    inout wire b2_c4,
    inout wire b2_c4_not,
    inout wire b2_c5,
    inout wire b2_c5_not,
    inout wire b2_c6,
    inout wire b2_c6_not,
    inout wire b2_c7,
    inout wire b2_c7_not,
    inout wire x0_c0_f,
    inout wire x0_c0_f_not,
    inout wire x1_c0_f,
    inout wire x1_c0_f_not,
    inout wire x0_b0_f,
    inout wire x0_b0_f_not,
    inout wire x0_c0_b,
    inout wire x0_c0_b_not,
    inout wire b0_r2_b,
    inout wire b0_r2_b_not,
    inout wire b0_r3_b,
    inout wire b0_r3_b_not,
    inout wire b0_r4_b,
    inout wire b0_r4_b_not,
    inout wire b0_r5_b,
    inout wire b0_r5_b_not,
    inout wire b0_r6_b,
    inout wire b0_r6_b_not,
    inout wire b0_r7_b,
    inout wire b0_r7_b_not,
    inout wire x0_a7_f,
    inout wire x0_a7_f_not,
    inout wire x0_a7_b,
    inout wire x0_a7_b_not,
    inout wire x1_b0_f,
    inout wire x1_b0_f_not,
    inout wire p2,
    inout wire p2_not,
    inout wire x1_c0_b,
    inout wire x1_c0_b_not,
    inout wire b2_r0_b,
    inout wire b2_r0_b_not,
    inout wire b2_r1_b,
    inout wire b2_r1_b_not,
    inout wire b2_r2_b,
    inout wire b2_r2_b_not,
    inout wire b2_r3_b,
    inout wire b2_r3_b_not,
    inout wire b2_r4_b,
    inout wire b2_r4_b_not,
    inout wire b2_r5_b,
    inout wire b2_r5_b_not,
    inout wire b2_r6_b,
    inout wire b2_r6_b_not,
    inout wire b2_r7_b,
    inout wire b2_r7_b_not,
    inout wire b3_c0,
    inout wire b3_c0_not,
    inout wire b3_q0,
    inout wire b3_q0_not,
    inout wire b3_p0,
    inout wire b3_p0_not,
    inout wire b3_q1,
    inout wire b3_q1_not,
    inout wire b3_p1,
    inout wire b3_p1_not,
    inout wire b3_c1,
    inout wire b3_c1_not,
    inout wire b3_q2,
    inout wire b3_q2_not,
    inout wire b3_p2,
    inout wire b3_p2_not,
    inout wire b3_q3,
    inout wire b3_q3_not,
    inout wire b3_p3,
    inout wire b3_p3_not,
    inout wire b3_q4,
    inout wire b3_q4_not,
    inout wire b3_p4,
    inout wire b3_p4_not,
    inout wire b3_q5,
    inout wire b3_q5_not,
    inout wire b3_p5,
    inout wire b3_p5_not,
    inout wire b3_q6,
    inout wire b3_q6_not,
    inout wire b3_p6,
    inout wire b3_p6_not,
    inout wire b3_q7,
    inout wire b3_q7_not,
    inout wire b3_p7,
    inout wire b3_p7_not,
    inout wire b3_c3,
    inout wire b3_c3_not,
    inout wire b3_c4,
    inout wire b3_c4_not,
    inout wire b3_c5,
    inout wire b3_c5_not,
    inout wire b3_c6,
    inout wire b3_c6_not,
    inout wire b3_c7,
    inout wire b3_c7_not,
    inout wire x2_c0_f,
    inout wire x2_c0_f_not,
    inout wire x2_b0_f,
    inout wire x2_b0_f_not,
    inout wire p3,
    inout wire p3_not,
    inout wire x2_c0_b,
    inout wire x2_c0_b_not,
    inout wire b3_r0_b,
    inout wire b3_r0_b_not,
    inout wire b3_r1_b,
    inout wire b3_r1_b_not,
    inout wire b3_r2_b,
    inout wire b3_r2_b_not,
    inout wire b3_r3_b,
    inout wire b3_r3_b_not,
    inout wire b3_r4_b,
    inout wire b3_r4_b_not,
    inout wire b3_r5_b,
    inout wire b3_r5_b_not,
    inout wire b3_r6_b,
    inout wire b3_r6_b_not,
    inout wire b3_r7_b,
    inout wire b3_r7_b_not,
    inout wire b4_c0,
    inout wire b4_c0_not,
    inout wire b4_q0,
    inout wire b4_q0_not,
    inout wire b4_p0,
    inout wire b4_p0_not,
    inout wire b4_q1,
    inout wire b4_q1_not,
    inout wire b4_p1,
    inout wire b4_p1_not,
    inout wire b4_c1,
    inout wire b4_c1_not,
    inout wire b4_q2,
    inout wire b4_q2_not,
    inout wire b4_p2,
    inout wire b4_p2_not,
    inout wire b4_q3,
    inout wire b4_q3_not,
    inout wire b4_p3,
    inout wire b4_p3_not,
    inout wire b4_q4,
    inout wire b4_q4_not,
    inout wire b4_p4,
    inout wire b4_p4_not,
    inout wire b4_q5,
    inout wire b4_q5_not,
    inout wire b4_p5,
    inout wire b4_p5_not,
    inout wire b4_q6,
    inout wire b4_q6_not,
    inout wire b4_p6,
    inout wire b4_p6_not,
    inout wire b4_q7,
    inout wire b4_q7_not,
    inout wire b4_p7,
    inout wire b4_p7_not,
    inout wire b4_c3,
    inout wire b4_c3_not,
    inout wire b4_c4,
    inout wire b4_c4_not,
    inout wire b4_c5,
    inout wire b4_c5_not,
    inout wire b4_c6,
    inout wire b4_c6_not,
    inout wire b4_c7,
    inout wire b4_c7_not,
    inout wire x3_c0_f,
    inout wire x3_c0_f_not,
    inout wire x3_b0_f,
    inout wire x3_b0_f_not,
    inout wire p4,
    inout wire p4_not,
    inout wire x3_c0_b,
    inout wire x3_c0_b_not,
    inout wire b4_r0_b,
    inout wire b4_r0_b_not,
    inout wire b4_r1_b,
    inout wire b4_r1_b_not,
    inout wire b4_r2_b,
    inout wire b4_r2_b_not,
    inout wire b4_r3_b,
    inout wire b4_r3_b_not,
    inout wire b4_r4_b,
    inout wire b4_r4_b_not,
    inout wire b4_r5_b,
    inout wire b4_r5_b_not,
    inout wire b4_r6_b,
    inout wire b4_r6_b_not,
    inout wire b4_r7_b,
    inout wire b4_r7_b_not,
    inout wire b5_c0,
    inout wire b5_c0_not,
    inout wire b5_q0,
    inout wire b5_q0_not,
    inout wire b5_p0,
    inout wire b5_p0_not,
    inout wire b5_q1,
    inout wire b5_q1_not,
    inout wire b5_p1,
    inout wire b5_p1_not,
    inout wire b5_c1,
    inout wire b5_c1_not,
    inout wire b5_q2,
    inout wire b5_q2_not,
    inout wire b5_p2,
    inout wire b5_p2_not,
    inout wire b5_q3,
    inout wire b5_q3_not,
    inout wire b5_p3,
    inout wire b5_p3_not,
    inout wire b5_q4,
    inout wire b5_q4_not,
    inout wire b5_p4,
    inout wire b5_p4_not,
    inout wire b5_q5,
    inout wire b5_q5_not,
    inout wire b5_p5,
    inout wire b5_p5_not,
    inout wire b5_q6,
    inout wire b5_q6_not,
    inout wire b5_p6,
    inout wire b5_p6_not,
    inout wire b5_q7,
    inout wire b5_q7_not,
    inout wire b5_p7,
    inout wire b5_p7_not,
    inout wire b5_c3,
    inout wire b5_c3_not,
    inout wire b5_c4,
    inout wire b5_c4_not,
    inout wire b5_c5,
    inout wire b5_c5_not,
    inout wire b5_c6,
    inout wire b5_c6_not,
    inout wire b5_c7,
    inout wire b5_c7_not,
    inout wire x4_c0_f,
    inout wire x4_c0_f_not,
    inout wire x4_b0_f,
    inout wire x4_b0_f_not,
    inout wire p5,
    inout wire p5_not,
    inout wire x4_c0_b,
    inout wire x4_c0_b_not,
    inout wire b5_r0_b,
    inout wire b5_r0_b_not,
    inout wire b5_r1_b,
    inout wire b5_r1_b_not,
    inout wire b5_r2_b,
    inout wire b5_r2_b_not,
    inout wire b5_r3_b,
    inout wire b5_r3_b_not,
    inout wire b5_r4_b,
    inout wire b5_r4_b_not,
    inout wire b5_r5_b,
    inout wire b5_r5_b_not,
    inout wire b5_r6_b,
    inout wire b5_r6_b_not,
    inout wire b5_r7_b,
    inout wire b5_r7_b_not,
    inout wire b6_c0,
    inout wire b6_c0_not,
    inout wire b6_q0,
    inout wire b6_q0_not,
    inout wire b6_p0,
    inout wire b6_p0_not,
    inout wire b6_q1,
    inout wire b6_q1_not,
    inout wire b6_p1,
    inout wire b6_p1_not,
    inout wire b6_c1,
    inout wire b6_c1_not,
    inout wire b6_q2,
    inout wire b6_q2_not,
    inout wire b6_p2,
    inout wire b6_p2_not,
    inout wire b6_q3,
    inout wire b6_q3_not,
    inout wire b6_p3,
    inout wire b6_p3_not,
    inout wire b6_q4,
    inout wire b6_q4_not,
    inout wire b6_p4,
    inout wire b6_p4_not,
    inout wire b6_q5,
    inout wire b6_q5_not,
    inout wire b6_p5,
    inout wire b6_p5_not,
    inout wire b6_q6,
    inout wire b6_q6_not,
    inout wire b6_p6,
    inout wire b6_p6_not,
    inout wire b6_q7,
    inout wire b6_q7_not,
    inout wire b6_p7,
    inout wire b6_p7_not,
    inout wire b6_c3,
    inout wire b6_c3_not,
    inout wire b6_c4,
    inout wire b6_c4_not,
    inout wire b6_c5,
    inout wire b6_c5_not,
    inout wire b6_c6,
    inout wire b6_c6_not,
    inout wire b6_c7,
    inout wire b6_c7_not,
    inout wire x5_c0_f,
    inout wire x5_c0_f_not,
    inout wire x5_b0_f,
    inout wire x5_b0_f_not,
    inout wire p6,
    inout wire p6_not,
    inout wire x5_c0_b,
    inout wire x5_c0_b_not,
    inout wire b6_r0_b,
    inout wire b6_r0_b_not,
    inout wire b6_r1_b,
    inout wire b6_r1_b_not,
    inout wire b6_r2_b,
    inout wire b6_r2_b_not,
    inout wire b6_r3_b,
    inout wire b6_r3_b_not,
    inout wire b6_r4_b,
    inout wire b6_r4_b_not,
    inout wire b6_r5_b,
    inout wire b6_r5_b_not,
    inout wire b6_r6_b,
    inout wire b6_r6_b_not,
    inout wire b6_r7_b,
    inout wire b6_r7_b_not,
    inout wire b7_c0,
    inout wire b7_c0_not,
    inout wire b7_q0,
    inout wire b7_q0_not,
    inout wire b7_p0,
    inout wire b7_p0_not,
    inout wire b7_q1,
    inout wire b7_q1_not,
    inout wire b7_p1,
    inout wire b7_p1_not,
    inout wire b7_c1,
    inout wire b7_c1_not,
    inout wire b7_q2,
    inout wire b7_q2_not,
    inout wire b7_p2,
    inout wire b7_p2_not,
    inout wire b7_q3,
    inout wire b7_q3_not,
    inout wire b7_p3,
    inout wire b7_p3_not,
    inout wire b7_q4,
    inout wire b7_q4_not,
    inout wire b7_p4,
    inout wire b7_p4_not,
    inout wire b7_q5,
    inout wire b7_q5_not,
    inout wire b7_p5,
    inout wire b7_p5_not,
    inout wire b7_q6,
    inout wire b7_q6_not,
    inout wire b7_p6,
    inout wire b7_p6_not,
    inout wire b7_q7,
    inout wire b7_q7_not,
    inout wire b7_p7,
    inout wire b7_p7_not,
    inout wire b7_c3,
    inout wire b7_c3_not,
    inout wire b7_c4,
    inout wire b7_c4_not,
    inout wire b7_c5,
    inout wire b7_c5_not,
    inout wire b7_c6,
    inout wire b7_c6_not,
    inout wire b7_c7,
    inout wire b7_c7_not,
    inout wire x6_c0_f,
    inout wire x6_c0_f_not,
    inout wire x6_b0_f,
    inout wire x6_b0_f_not,
    inout wire p7,
    inout wire p7_not,
    inout wire x6_c0_b,
    inout wire x6_c0_b_not,
    inout wire b7_r0_b,
    inout wire b7_r0_b_not,
    inout wire b7_r1_b,
    inout wire b7_r1_b_not,
    inout wire b7_r2_b,
    inout wire b7_r2_b_not,
    inout wire b7_r3_b,
    inout wire b7_r3_b_not,
    inout wire b7_r4_b,
    inout wire b7_r4_b_not,
    inout wire b7_r5_b,
    inout wire b7_r5_b_not,
    inout wire b7_r6_b,
    inout wire b7_r6_b_not,
    inout wire b7_r7_b,
    inout wire b7_r7_b_not,
    inout wire p8,
    inout wire p8_not,
    inout wire p9,
    inout wire p9_not,
    inout wire p10,
    inout wire p10_not,
    inout wire p11,
    inout wire p11_not,
    inout wire p12,
    inout wire p12_not,
    inout wire p13,
    inout wire p13_not,
    inout wire p14,
    inout wire p14_not,
    inout wire p15,
    inout wire p15_not,
    inout wire b6_c2,
    inout wire b6_c2_not,
    inout wire b7_c2,
    inout wire b7_c2_not,
    inout wire b4_c2,
    inout wire b4_c2_not,
    inout wire b3_c2,
    inout wire b3_c2_not,
    inout wire b2_c2,
    inout wire b2_c2_not,
    inout wire b5_c2,
    inout wire b5_c2_not,
    inout wire b2_not,
    inout wire b2,
    inout wire b3_not,
    inout wire b3,
    inout wire b4_not,
    inout wire b4,
    inout wire b5_not,
    inout wire b5,
    inout wire b6_not,
    inout wire b6,
    inout wire b7_not,
    inout wire b7
);

    // Internal nets that connect CCNOT / 8b_FA_ripple cells
    wire b0_r1, b0_r1_not, b0_r2, b0_r2_not, b0_r3, b0_r3_not, b0_r4, b0_r4_not;
    wire b0_r5, b0_r5_not, b0_r6, b0_r6_not, b0_r7, b0_r7_not, b1_r0, b1_r0_not;
    wire b1_r1, b1_r1_not, b1_r2, b1_r2_not, b1_r3, b1_r3_not, b1_r4, b1_r4_not;
    wire b1_r5, b1_r5_not, b1_r6, b1_r6_not, b1_r7, b1_r7_not, b2_r0, b2_r0_not;
    wire b2_r1, b2_r1_not, b2_r2, b2_r2_not, b2_r3, b2_r3_not, b2_r4, b2_r4_not;
    wire b2_r5, b2_r5_not, b2_r6, b2_r6_not, b2_r7, b2_r7_not, b3_r0, b3_r0_not;
    wire b3_r1, b3_r1_not, b3_r2, b3_r2_not, b3_r3, b3_r3_not, b3_r4, b3_r4_not;
    wire b3_r5, b3_r5_not, b3_r6, b3_r6_not, b3_r7, b3_r7_not, b4_r0, b4_r0_not;
    wire b4_r1, b4_r1_not, b4_r2, b4_r2_not, b4_r3, b4_r3_not, b4_r4, b4_r4_not;
    wire b4_r5, b4_r5_not, b4_r6, b4_r6_not, b4_r7, b4_r7_not, b5_r0, b5_r0_not;
    wire b5_r1, b5_r1_not, b5_r2, b5_r2_not, b5_r3, b5_r3_not, b5_r4, b5_r4_not;
    wire b5_r5, b5_r5_not, b5_r6, b5_r6_not, b5_r7, b5_r7_not, b6_r0, b6_r0_not;
    wire b6_r1, b6_r1_not, b6_r2, b6_r2_not, b6_r3, b6_r3_not, b6_r4, b6_r4_not;
    wire b6_r5, b6_r5_not, b6_r6, b6_r6_not, b6_r7, b6_r7_not, b7_r0, b7_r0_not;
    wire b7_r1, b7_r1_not, b7_r2, b7_r2_not, b7_r3, b7_r3_not, b7_r4, b7_r4_not;
    wire b7_r5, b7_r5_not, b7_r6, b7_r6_not, b7_r7, b7_r7_not, net1, net10, net11;
    wire net12, net13, net14, net2, net3, net4, net5, net6, net7, net8, net9, x0_s1;
    wire x0_s1_not, x0_s2, x0_s2_not, x0_s3, x0_s3_not, x0_s4, x0_s4_not, x0_s5;
    wire x0_s5_not, x0_s6, x0_s6_not, x0_s7, x0_s7_not, x0_s8, x0_s8_not, x1_s1;
    wire x1_s1_not, x1_s2, x1_s2_not, x1_s3, x1_s3_not, x1_s4, x1_s4_not, x1_s5;
    wire x1_s5_not, x1_s6, x1_s6_not, x1_s7, x1_s7_not, x1_s8, x1_s8_not, x2_s1;
    wire x2_s1_not, x2_s2, x2_s2_not, x2_s3, x2_s3_not, x2_s4, x2_s4_not, x2_s5;
    wire x2_s5_not, x2_s6, x2_s6_not, x2_s7, x2_s7_not, x2_s8, x2_s8_not, x3_s1;
    wire x3_s1_not, x3_s2, x3_s2_not, x3_s3, x3_s3_not, x3_s4, x3_s4_not, x3_s5;
    wire x3_s5_not, x3_s6, x3_s6_not, x3_s7, x3_s7_not, x3_s8, x3_s8_not, x4_s1;
    wire x4_s1_not, x4_s2, x4_s2_not, x4_s3, x4_s3_not, x4_s4, x4_s4_not, x4_s5;
    wire x4_s5_not, x4_s6, x4_s6_not, x4_s7, x4_s7_not, x4_s8, x4_s8_not, x5_s1;
    wire x5_s1_not, x5_s2, x5_s2_not, x5_s3, x5_s3_not, x5_s4, x5_s4_not, x5_s5;
    wire x5_s5_not, x5_s6, x5_s6_not, x5_s7, x5_s7_not, x5_s8, x5_s8_not;

    CCNOT x2 ( a0, b0, VSS, VDD, a0_not, b0_not, p0, b0_c0, b0_p0, b0_q0, p0_not, b0_p0_not, b0_q0_not, b0_c0_not );
    CCNOT x4 ( a0, b1, VSS, VDD, a0_not, b1_not, b1_r0, b1_c0, b1_p0, b1_q0, b1_r0_not, b1_p0_not, b1_q0_not, b1_c0_not );
    CCNOT x5 ( a1, b1, VSS, VDD, a1_not, b1_not, b1_r1, b1_c1, b1_p1, b1_q1, b1_r1_not, b1_p1_not, b1_q1_not, b1_c1_not );
    CCNOT x6 ( a2, b1, VSS, VDD, a2_not, b1_not, b1_r2, b1_c2, b1_p2, b1_q2, b1_r2_not, b1_p2_not, b1_q2_not, b1_c2_not );
    CCNOT x7 ( a3, b1, VSS, VDD, a3_not, b1_not, b1_r3, b1_c3, b1_p3, b1_q3, b1_r3_not, b1_p3_not, b1_q3_not, b1_c3_not );
    CCNOT x8 ( a4, b1, VSS, VDD, a4_not, b1_not, b1_r4, b1_c4, b1_p4, b1_q4, b1_r4_not, b1_p4_not, b1_q4_not, b1_c4_not );
    CCNOT x9 ( a5, b1, VSS, VDD, a5_not, b1_not, b1_r5, b1_c5, b1_p5, b1_q5, b1_r5_not, b1_p5_not, b1_q5_not, b1_c5_not );
    CCNOT x10 ( a6, b1, VSS, VDD, a6_not, b1_not, b1_r6, b1_c6, b1_p6, b1_q6, b1_r6_not, b1_p6_not, b1_q6_not, b1_c6_not );
    CCNOT x11 ( a7, b1, VSS, VDD, a7_not, b1_not, b1_r7, b1_c7, b1_p7, b1_q7, b1_r7_not, b1_p7_not, b1_q7_not, b1_c7_not );
    CCNOT x13 ( a1, b0, VSS, VDD, a1_not, b0_not, b0_r1, b0_c1, b0_p1, b0_q1, b0_r1_not, b0_p1_not, b0_q1_not, b0_c1_not );
    CCNOT x14 ( a2, b0, VSS, VDD, a2_not, b0_not, b0_r2, b0_c2, b0_p2, b0_q2, b0_r2_not, b0_p2_not, b0_q2_not, b0_c2_not );
    CCNOT x15 ( a3, b0, VSS, VDD, a3_not, b0_not, b0_r3, b0_c3, b0_p3, b0_q3, b0_r3_not, b0_p3_not, b0_q3_not, b0_c3_not );
    CCNOT x16 ( a4, b0, VSS, VDD, a4_not, b0_not, b0_r4, b0_c4, b0_p4, b0_q4, b0_r4_not, b0_p4_not, b0_q4_not, b0_c4_not );
    CCNOT x17 ( a5, b0, VSS, VDD, a5_not, b0_not, b0_r5, b0_c5, b0_p5, b0_q5, b0_r5_not, b0_p5_not, b0_q5_not, b0_c5_not );
    CCNOT x18 ( a6, b0, VSS, VDD, a6_not, b0_not, b0_r6, b0_c6, b0_p6, b0_q6, b0_r6_not, b0_p6_not, b0_q6_not, b0_c6_not );
    CCNOT x19 ( a7, b0, VSS, VDD, a7_not, b0_not, b0_r7, b0_c7, b0_p7, b0_q7, b0_r7_not, b0_p7_not, b0_q7_not, b0_c7_not );
    CCNOT x12 ( a0, b2, VSS, VDD, a0_not, b2_not, b2_r0, b2_c0, b2_p0, b2_q0, b2_r0_not, b2_p0_not, b2_q0_not, b2_c0_not );
    CCNOT x20 ( a1, b2, VSS, VDD, a1_not, b2_not, b2_r1, b2_c1, b2_p1, b2_q1, b2_r1_not, b2_p1_not, b2_q1_not, b2_c1_not );
    CCNOT x21 ( a2, b2, VSS, VDD, a2_not, b2_not, b2_r2, b2_c2, b2_p2, b2_q2, b2_r2_not, b2_p2_not, b2_q2_not, b2_c2_not );
    CCNOT x22 ( a3, b2, VSS, VDD, a3_not, b2_not, b2_r3, b2_c3, b2_p3, b2_q3, b2_r3_not, b2_p3_not, b2_q3_not, b2_c3_not );
    CCNOT x23 ( a4, b2, VSS, VDD, a4_not, b2_not, b2_r4, b2_c4, b2_p4, b2_q4, b2_r4_not, b2_p4_not, b2_q4_not, b2_c4_not );
    CCNOT x24 ( a5, b2, VSS, VDD, a5_not, b2_not, b2_r5, b2_c5, b2_p5, b2_q5, b2_r5_not, b2_p5_not, b2_q5_not, b2_c5_not );
    CCNOT x25 ( a6, b2, VSS, VDD, a6_not, b2_not, b2_r6, b2_c6, b2_p6, b2_q6, b2_r6_not, b2_p6_not, b2_q6_not, b2_c6_not );
    CCNOT x26 ( a7, b2, VSS, VDD, a7_not, b2_not, b2_r7, b2_c7, b2_p7, b2_q7, b2_r7_not, b2_p7_not, b2_q7_not, b2_c7_not );
    fa8b_rev x27 ( VDD, VSS, x0_c0_f, x0_c0_b, x0_c0_f_not, x0_c0_b_not, p1, b1_r0, p1_not, b1_r0_not, b0_r1, b0_r1_b, b0_r1_b_not, b0_r1_not, b1_r1, x0_s1, b1_r1_not, x0_s1_not, b0_r2, b0_r2_b, b0_r2_not, b0_r2_b_not, x0_s2, b1_r2, x0_s2_not, b1_r2_not, b0_r3_b, b0_r3, b0_r3_not, b0_r3_b_not, x0_s3, b1_r3, x0_s3_not, b1_r3_not, b0_r4_b, b0_r4, b0_r4_not, b0_r4_b_not, x0_s4, b1_r4, b1_r4_not, x0_s4_not, b0_r5_b, b0_r5, b0_r5_b_not, b0_r5_not, b1_r5, x0_s5, b1_r5_not, x0_s5_not, b0_r6, b0_r6_b, b0_r6_b_not, b0_r6_not, b1_r6, x0_s6, b1_r6_not, x0_s6_not, b0_r7, b0_r7_b, b0_r7_b_not, b0_r7_not, x0_s7, b1_r7, b1_r7_not, x0_s7_not, x0_a7_b, x0_a7_f, x0_a7_b_not, x0_a7_f_not, net1, net2, net1, net2 );
    fa8b_rev x1 ( VDD, VSS, x1_c0_f, x1_c0_b, x1_c0_f_not, x1_c0_b_not, p2, x0_s1, p2_not, x0_s1_not, b2_r0, b2_r0_b, b2_r0_b_not, b2_r0_not, x0_s2, x1_s1, x0_s2_not, x1_s1_not, b2_r1, b2_r1_b, b2_r1_not, b2_r1_b_not, x1_s2, x0_s3, x1_s2_not, x0_s3_not, b2_r2_b, b2_r2, b2_r2_not, b2_r2_b_not, x1_s3, x0_s4, x1_s3_not, x0_s4_not, b2_r3_b, b2_r3, b2_r3_not, b2_r3_b_not, x1_s4, x0_s5, x0_s5_not, x1_s4_not, b2_r4_b, b2_r4, b2_r4_b_not, b2_r4_not, x0_s6, x1_s5, x0_s6_not, x1_s5_not, b2_r5, b2_r5_b, b2_r5_b_not, b2_r5_not, x0_s7, x1_s6, x0_s7_not, x1_s6_not, b2_r6, b2_r6_b, b2_r6_b_not, b2_r6_not, x1_s7, x0_s8, x0_s8_not, x1_s7_not, b2_r7_b, b2_r7, b2_r7_b_not, b2_r7_not, net3, net4, net3, net4 );
    CCNOT x3 ( a0, b3, VSS, VDD, a0_not, b3_not, b3_r0, b3_c0, b3_p0, b3_q0, b3_r0_not, b3_p0_not, b3_q0_not, b3_c0_not );
    CCNOT x28 ( a1, b3, VSS, VDD, a1_not, b3_not, b3_r1, b3_c1, b3_p1, b3_q1, b3_r1_not, b3_p1_not, b3_q1_not, b3_c1_not );
    CCNOT x29 ( a2, b3, VSS, VDD, a2_not, b3_not, b3_r2, b3_c2, b3_p2, b3_q2, b3_r2_not, b3_p2_not, b3_q2_not, b3_c2_not );
    CCNOT x30 ( a3, b3, VSS, VDD, a3_not, b3_not, b3_r3, b3_c3, b3_p3, b3_q3, b3_r3_not, b3_p3_not, b3_q3_not, b3_c3_not );
    CCNOT x31 ( a4, b3, VSS, VDD, a4_not, b3_not, b3_r4, b3_c4, b3_p4, b3_q4, b3_r4_not, b3_p4_not, b3_q4_not, b3_c4_not );
    CCNOT x32 ( a5, b3, VSS, VDD, a5_not, b3_not, b3_r5, b3_c5, b3_p5, b3_q5, b3_r5_not, b3_p5_not, b3_q5_not, b3_c5_not );
    CCNOT x33 ( a6, b3, VSS, VDD, a6_not, b3_not, b3_r6, b3_c6, b3_p6, b3_q6, b3_r6_not, b3_p6_not, b3_q6_not, b3_c6_not );
    CCNOT x34 ( a7, b3, VSS, VDD, a7_not, b3_not, b3_r7, b3_c7, b3_p7, b3_q7, b3_r7_not, b3_p7_not, b3_q7_not, b3_c7_not );
    fa8b_rev x35 ( VDD, VSS, x2_c0_f, x2_c0_b, x2_c0_f_not, x2_c0_b_not, p3, x1_s1, p3_not, x1_s1_not, b3_r0, b3_r0_b, b3_r0_b_not, b3_r0_not, x1_s2, x2_s1, x1_s2_not, x2_s1_not, b3_r1, b3_r1_b, b3_r1_not, b3_r1_b_not, x2_s2, x1_s3, x2_s2_not, x1_s3_not, b3_r2_b, b3_r2, b3_r2_not, b3_r2_b_not, x2_s3, x1_s4, x2_s3_not, x1_s4_not, b3_r3_b, b3_r3, b3_r3_not, b3_r3_b_not, x2_s4, x1_s5, x1_s5_not, x2_s4_not, b3_r4_b, b3_r4, b3_r4_b_not, b3_r4_not, x1_s6, x2_s5, x1_s6_not, x2_s5_not, b3_r5, b3_r5_b, b3_r5_b_not, b3_r5_not, x1_s7, x2_s6, x1_s7_not, x2_s6_not, b3_r6, b3_r6_b, b3_r6_b_not, b3_r6_not, x2_s7, x1_s8, x1_s8_not, x2_s7_not, b3_r7_b, b3_r7, b3_r7_b_not, b3_r7_not, net5, net6, net5, net6 );
    CCNOT x36 ( a0, b4, VSS, VDD, a0_not, b4_not, b4_r0, b4_c0, b4_p0, b4_q0, b4_r0_not, b4_p0_not, b4_q0_not, b4_c0_not );
    CCNOT x37 ( a1, b4, VSS, VDD, a1_not, b4_not, b4_r1, b4_c1, b4_p1, b4_q1, b4_r1_not, b4_p1_not, b4_q1_not, b4_c1_not );
    CCNOT x38 ( a2, b4, VSS, VDD, a2_not, b4_not, b4_r2, b4_c2, b4_p2, b4_q2, b4_r2_not, b4_p2_not, b4_q2_not, b4_c2_not );
    CCNOT x39 ( a3, b4, VSS, VDD, a3_not, b4_not, b4_r3, b4_c3, b4_p3, b4_q3, b4_r3_not, b4_p3_not, b4_q3_not, b4_c3_not );
    CCNOT x40 ( a4, b4, VSS, VDD, a4_not, b4_not, b4_r4, b4_c4, b4_p4, b4_q4, b4_r4_not, b4_p4_not, b4_q4_not, b4_c4_not );
    CCNOT x41 ( a5, b4, VSS, VDD, a5_not, b4_not, b4_r5, b4_c5, b4_p5, b4_q5, b4_r5_not, b4_p5_not, b4_q5_not, b4_c5_not );
    CCNOT x42 ( a6, b4, VSS, VDD, a6_not, b4_not, b4_r6, b4_c6, b4_p6, b4_q6, b4_r6_not, b4_p6_not, b4_q6_not, b4_c6_not );
    CCNOT x43 ( a7, b4, VSS, VDD, a7_not, b4_not, b4_r7, b4_c7, b4_p7, b4_q7, b4_r7_not, b4_p7_not, b4_q7_not, b4_c7_not );
    fa8b_rev x44 ( VDD, VSS, x3_c0_f, x3_c0_b, x3_c0_f_not, x3_c0_b_not, p4, x2_s1, p4_not, x2_s1_not, b4_r0, b4_r0_b, b4_r0_b_not, b4_r0_not, x2_s2, x3_s1, x2_s2_not, x3_s1_not, b4_r1, b4_r1_b, b4_r1_not, b4_r1_b_not, x3_s2, x2_s3, x3_s2_not, x2_s3_not, b4_r2_b, b4_r2, b4_r2_not, b4_r2_b_not, x3_s3, x2_s4, x3_s3_not, x2_s4_not, b4_r3_b, b4_r3, b4_r3_not, b4_r3_b_not, x3_s4, x2_s5, x2_s5_not, x3_s4_not, b4_r4_b, b4_r4, b4_r4_b_not, b4_r4_not, x2_s6, x3_s5, x2_s6_not, x3_s5_not, b4_r5, b4_r5_b, b4_r5_b_not, b4_r5_not, x2_s7, x3_s6, x2_s7_not, x3_s6_not, b4_r6, b4_r6_b, b4_r6_b_not, b4_r6_not, x3_s7, x2_s8, x2_s8_not, x3_s7_not, b4_r7_b, b4_r7, b4_r7_b_not, b4_r7_not, net7, net8, net7, net8 );
    CCNOT x45 ( a0, b5, VSS, VDD, a0_not, b5_not, b5_r0, b5_c0, b5_p0, b5_q0, b5_r0_not, b5_p0_not, b5_q0_not, b5_c0_not );
    CCNOT x46 ( a1, b5, VSS, VDD, a1_not, b5_not, b5_r1, b5_c1, b5_p1, b5_q1, b5_r1_not, b5_p1_not, b5_q1_not, b5_c1_not );
    CCNOT x47 ( a2, b5, VSS, VDD, a2_not, b5_not, b5_r2, b5_c2, b5_p2, b5_q2, b5_r2_not, b5_p2_not, b5_q2_not, b5_c2_not );
    CCNOT x48 ( a3, b5, VSS, VDD, a3_not, b5_not, b5_r3, b5_c3, b5_p3, b5_q3, b5_r3_not, b5_p3_not, b5_q3_not, b5_c3_not );
    CCNOT x49 ( a4, b5, VSS, VDD, a4_not, b5_not, b5_r4, b5_c4, b5_p4, b5_q4, b5_r4_not, b5_p4_not, b5_q4_not, b5_c4_not );
    CCNOT x50 ( a5, b5, VSS, VDD, a5_not, b5_not, b5_r5, b5_c5, b5_p5, b5_q5, b5_r5_not, b5_p5_not, b5_q5_not, b5_c5_not );
    CCNOT x51 ( a6, b5, VSS, VDD, a6_not, b5_not, b5_r6, b5_c6, b5_p6, b5_q6, b5_r6_not, b5_p6_not, b5_q6_not, b5_c6_not );
    CCNOT x52 ( a7, b5, VSS, VDD, a7_not, b5_not, b5_r7, b5_c7, b5_p7, b5_q7, b5_r7_not, b5_p7_not, b5_q7_not, b5_c7_not );
    fa8b_rev x53 ( VDD, VSS, x4_c0_f, x4_c0_b, x4_c0_f_not, x4_c0_b_not, p5, x3_s1, p5_not, x3_s1_not, b5_r0, b5_r0_b, b5_r0_b_not, b5_r0_not, x3_s2, x4_s1, x3_s2_not, x4_s1_not, b5_r1, b5_r1_b, b5_r1_not, b5_r1_b_not, x4_s2, x3_s3, x4_s2_not, x3_s3_not, b5_r2_b, b5_r2, b5_r2_not, b5_r2_b_not, x4_s3, x3_s4, x4_s3_not, x3_s4_not, b5_r3_b, b5_r3, b5_r3_not, b5_r3_b_not, x4_s4, x3_s5, x3_s5_not, x4_s4_not, b5_r4_b, b5_r4, b5_r4_b_not, b5_r4_not, x3_s6, x4_s5, x3_s6_not, x4_s5_not, b5_r5, b5_r5_b, b5_r5_b_not, b5_r5_not, x3_s7, x4_s6, x3_s7_not, x4_s6_not, b5_r6, b5_r6_b, b5_r6_b_not, b5_r6_not, x4_s7, x3_s8, x3_s8_not, x4_s7_not, b5_r7_b, b5_r7, b5_r7_b_not, b5_r7_not, net9, net10, net9, net10 );
    CCNOT x54 ( a0, b6, VSS, VDD, a0_not, b6_not, b6_r0, b6_c0, b6_p0, b6_q0, b6_r0_not, b6_p0_not, b6_q0_not, b6_c0_not );
    CCNOT x55 ( a1, b6, VSS, VDD, a1_not, b6_not, b6_r1, b6_c1, b6_p1, b6_q1, b6_r1_not, b6_p1_not, b6_q1_not, b6_c1_not );
    CCNOT x56 ( a2, b6, VSS, VDD, a2_not, b6_not, b6_r2, b6_c2, b6_p2, b6_q2, b6_r2_not, b6_p2_not, b6_q2_not, b6_c2_not );
    CCNOT x57 ( a3, b6, VSS, VDD, a3_not, b6_not, b6_r3, b6_c3, b6_p3, b6_q3, b6_r3_not, b6_p3_not, b6_q3_not, b6_c3_not );
    CCNOT x58 ( a4, b6, VSS, VDD, a4_not, b6_not, b6_r4, b6_c4, b6_p4, b6_q4, b6_r4_not, b6_p4_not, b6_q4_not, b6_c4_not );
    CCNOT x59 ( a5, b6, VSS, VDD, a5_not, b6_not, b6_r5, b6_c5, b6_p5, b6_q5, b6_r5_not, b6_p5_not, b6_q5_not, b6_c5_not );
    CCNOT x60 ( a6, b6, VSS, VDD, a6_not, b6_not, b6_r6, b6_c6, b6_p6, b6_q6, b6_r6_not, b6_p6_not, b6_q6_not, b6_c6_not );
    CCNOT x61 ( a7, b6, VSS, VDD, a7_not, b6_not, b6_r7, b6_c7, b6_p7, b6_q7, b6_r7_not, b6_p7_not, b6_q7_not, b6_c7_not );
    fa8b_rev x62 ( VDD, VSS, x5_c0_f, x5_c0_b, x5_c0_f_not, x5_c0_b_not, p6, x4_s1, p6_not, x4_s1_not, b6_r0, b6_r0_b, b6_r0_b_not, b6_r0_not, x4_s2, x5_s1, x4_s2_not, x5_s1_not, b6_r1, b6_r1_b, b6_r1_not, b6_r1_b_not, x5_s2, x4_s3, x5_s2_not, x4_s3_not, b6_r2_b, b6_r2, b6_r2_not, b6_r2_b_not, x5_s3, x4_s4, x5_s3_not, x4_s4_not, b6_r3_b, b6_r3, b6_r3_not, b6_r3_b_not, x5_s4, x4_s5, x4_s5_not, x5_s4_not, b6_r4_b, b6_r4, b6_r4_b_not, b6_r4_not, x4_s6, x5_s5, x4_s6_not, x5_s5_not, b6_r5, b6_r5_b, b6_r5_b_not, b6_r5_not, x4_s7, x5_s6, x4_s7_not, x5_s6_not, b6_r6, b6_r6_b, b6_r6_b_not, b6_r6_not, x5_s7, x4_s8, x4_s8_not, x5_s7_not, b6_r7_b, b6_r7, b6_r7_b_not, b6_r7_not, net11, net12, net11, net12 );
    CCNOT x63 ( a0, b7, VSS, VDD, a0_not, b7_not, b7_r0, b7_c0, b7_p0, b7_q0, b7_r0_not, b7_p0_not, b7_q0_not, b7_c0_not );
    CCNOT x64 ( a1, b7, VSS, VDD, a1_not, b7_not, b7_r1, b7_c1, b7_p1, b7_q1, b7_r1_not, b7_p1_not, b7_q1_not, b7_c1_not );
    CCNOT x65 ( a2, b7, VSS, VDD, a2_not, b7_not, b7_r2, b7_c2, b7_p2, b7_q2, b7_r2_not, b7_p2_not, b7_q2_not, b7_c2_not );
    CCNOT x66 ( a3, b7, VSS, VDD, a3_not, b7_not, b7_r3, b7_c3, b7_p3, b7_q3, b7_r3_not, b7_p3_not, b7_q3_not, b7_c3_not );
    CCNOT x67 ( a4, b7, VSS, VDD, a4_not, b7_not, b7_r4, b7_c4, b7_p4, b7_q4, b7_r4_not, b7_p4_not, b7_q4_not, b7_c4_not );
    CCNOT x68 ( a5, b7, VSS, VDD, a5_not, b7_not, b7_r5, b7_c5, b7_p5, b7_q5, b7_r5_not, b7_p5_not, b7_q5_not, b7_c5_not );
    CCNOT x69 ( a6, b7, VSS, VDD, a6_not, b7_not, b7_r6, b7_c6, b7_p6, b7_q6, b7_r6_not, b7_p6_not, b7_q6_not, b7_c6_not );
    CCNOT x70 ( a7, b7, VSS, VDD, a7_not, b7_not, b7_r7, b7_c7, b7_p7, b7_q7, b7_r7_not, b7_p7_not, b7_q7_not, b7_c7_not );
    fa8b_rev x71 ( VDD, VSS, x6_c0_f, x6_c0_b, x6_c0_f_not, x6_c0_b_not, p7, x5_s1, p7_not, x5_s1_not, b7_r0, b7_r0_b, b7_r0_b_not, b7_r0_not, x5_s2, p8, x5_s2_not, p8_not, b7_r1, b7_r1_b, b7_r1_not, b7_r1_b_not, p9, x5_s3, p9_not, x5_s3_not, b7_r2_b, b7_r2, b7_r2_not, b7_r2_b_not, p10, x5_s4, p10_not, x5_s4_not, b7_r3_b, b7_r3, b7_r3_not, b7_r3_b_not, p11, x5_s5, x5_s5_not, p11_not, b7_r4_b, b7_r4, b7_r4_b_not, b7_r4_not, x5_s6, p12, x5_s6_not, p12_not, b7_r5, b7_r5_b, b7_r5_b_not, b7_r5_not, x5_s7, p13, x5_s7_not, p13_not, b7_r6, b7_r6_b, b7_r6_b_not, b7_r6_not, p14, x5_s8, x5_s8_not, p14_not, b7_r7_b, b7_r7, b7_r7_b_not, b7_r7_not, net13, net14, net13, net14 );

endmodule